driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.7

suites:
  - name: default
    run_list: snoopy-build::default
    attributes:
      snoopy_build:
        package_cloud_user: test
        package_cloud_token: test
        package_cloud_repo: test
        publish_artifacts: false
        build_version: <%=
          require_relative 'libraries/helpers'
          SnoopyBuildCookbook::Helpers.version
        %>
        build_revision: 1
