driver:
  name: vagrant
  forward_agent: yes
  customize:
    memory: 2048
  synced_folders:
    - ['.', '/snoopy']

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  # - name: centos-7.1
  # - name: centos-6.6
  # - name: centos-5.11
  # - name: debian-7.8
  # - name: debian-6.0.10
  # - name: freebsd-10.1
  #   run_list: freebsd::portsnap
  # - name: freebsd-9.3
  #   run_list:
  #     - freebsd::portsnap
  #     - freebsd::pkgng
  - name: ubuntu-14.04
  # - name: ubuntu-12.04

suites:
  - name: default
    run_list: snoopy-omnibus::default
    attributes:
      omnibus:
        build_version: <%=
          require 'net/http'
          Net::HTTP.get(URI('http://source.a2o.si/download/snoopy/' \
                            'snoopy-latest-version.txt')).strip
        %>
        build_iteration: 1
        build_user: omnibus
        build_user_group: omnibus
        staging_dir: /snoopy
        project_dir: /home/omnibus/snoopy
        # build_user_password: omnibus
        install_dir:         /opt/snoopy
      package_cloud:
        user: roboticcheese
        repo: snoopy
