language: ruby

install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential curl git ruby devscripts debhelper autoconf dh-autoreconf socat
  - gem install package_cloud

before_script:
  - git clone https://github.com/a2o/snoopy
  - cd snoopy
  - git checkout snoopy-`curl http://source.a2o.si/download/snoopy/snoopy-latest-version.txt`
  - git submodule init
  - git submodule update
  - ln -nfs contrib/debian .
  - mkdir -p build/m4
  - sed -i 's/rm /rm -f /' contrib/debian/rules
  - "sed -i '/^Maintainer: /s/.*/Maintainer: Jonathan Hartman <j@hartman.io>/' contrib/debian/control"

script:
  - sudo debuild --no-tgz-check -I.git -i'\.git/' -us -uc -b -v

after_script:
  - ls -la ~/libsnoopy*

env:
  global:
